### ISSUE TITLE
Capybara issues with Caracal mod (Fabric)

### ISSUE THREAD

**Issue by Monikaahh** [ZestyBlaze/Capybara-UAM#10]
On my Minecraft server, we installed this cute mod as well as the Caracal mod for Fabric. But when the Caracal and the Capybara are nearby, the Caracal seems to slide over onto the Capybara no matter what - even when on a leash or sitting- and causes the Capybara to forever be walking, which can be annoying because it just walks and teleports to me. (I hope I worded that right.)
I also posted this on the issues tab for the Caracal mod and I'm hoping this issue can be fixed so they can work together

Screenshot to show the problem:
(https://user-images.githubusercontent.com/107805586/174489588-d3a4af46-34f5-4087-b1f5-16edbdda2e67.png)

Edit: It seems like all mobs do this, which can be cute yet annoying since the Capybara no longer follows me when a mob is on top of it. I know it's intentional but is there a way to prevent mobs from sitting on top of the Capybara?

**Comment by ZestyBlaze** [comment]
Since this has been raised a couple times now about people wanting a way to disable this AI feature, I will work on a way to disable this AI of the Capybara with the config :)

**Comment by Ivan-Khar** [comment]
You could add e.isSitting() check. If mob is sitting then it shouldn't try to move towards the capybara

**Comment by Monikaahh** [comment]
> Since this has been raised a couple times now about people wanting a way to disable this AI feature, I will work on a way to disable this AI of the Capybara with the config :)

Thank you! Will it be taken it away permanently or be an option for people who don't want it? I don't want to get rid of that feature forever because it can be cute, just inconveniences me sometimes :')

**Comment by Monikaahh** [comment]
> You could add e.isSitting() check. If mob is sitting then it shouldn't try to move towards the capybara

Alright, thank you!

**Comment by ZestyBlaze** [comment]
> > Since this has been raised a couple times now about people wanting a way to disable this AI feature, I will work on a way to disable this AI of the Capybara with the config :)
> 
> Thank you! Will it be taken it away permanently or be an option for people who don't want it? I don't want to get rid of that feature forever because it can be cute, just inconveniences me sometimes :')

It will be a config option for those who don't want it, but I'll also check to see if the other entity is sitting and stuff to add more control to it

**Comment by ZestyBlaze** [comment]
Fixed in 1.0.6 and 1.0.7
