### ISSUE TITLE
Capybara Ticking Entity Crash

### ISSUE THREAD

**Issue by BearfootNick** [ZestyBlaze/Capybara-UAM#12]
Capybara is crashing the whole server creating a NoSuchFieldError

https://pastebin.com/sqHn524w

**Comment by ZestyBlaze** [comment]
Version of mod please

**Comment by BearfootNick** [comment]
> Version of mod please

Capybara 1.0.4

Running on

Fabric Modloader 13.3
Game Version 1.18.1

**Comment by ZestyBlaze** [comment]
Uninstall the mod and reinstall with version 1.18.1-1.0.6, that should fix it

**Comment by BearfootNick** [comment]
> Uninstall the mod and reinstall with version 1.18.1-1.0.6, that should fix it

Thank you for such a quick fix! My members were actually rioting when I had to remove it lol
