### ISSUE TITLE
Version 1.18.2-1.0.5 says that it's supposed to run with 1.19

### ISSUE THREAD

**Issue by thunfisch987** [ZestyBlaze/Capybara-UAM#13]
![Screenshot 2022-06-25 085602](https://user-images.githubusercontent.com/43795814/175762466-d7acdb9c-1692-4269-8552-bb6d0bd99d4e.png)
![Screenshot 2022-06-25 085445](https://user-images.githubusercontent.com/43795814/175762473-d5cd3f46-41a5-49e0-8eb5-72d5018a6bfe.png)
  
**Found the error**
in the fabric.mod.json file it says 1.19.x
![Screenshot 2022-06-25 085754](https://user-images.githubusercontent.com/43795814/175762509-5447dd6b-4f83-43e8-bcd4-2a535683c6f7.png)

**Comment by thunfisch987** [comment]
i would have opened a pull request but i couldn't find the 1.19 version/branch on here

**Comment by ZestyBlaze** [comment]
Yeah I always forget to change that file, give me 5 minutes and I'll push that fix for 1.18.2 and 1.18.1. I've achieved those broken files for you all
And yeah I need to push a 1.19 branch for Github
