### ISSUE TITLE
Crash with Capybara 2.0.0 - MC 1.19.2

### ISSUE THREAD

**Issue by Cynicizm** [ZestyBlaze/Capybara-UAM#23]
Updated the mod yesterday and my modpack crashes (can't launch the game).

https://pastebin.com/66yWKMiS

I know the crash says its Not Enough Crashes/Sodium's fault, but I played with them both in the previous day (before updating Capybara) and the game launched perfectly fine as usual.

Tried removing NEC/Sodium and this is what I got

https://pastebin.com/5BVXiyYA

Now it says that its kiwi's fault. As I said before, my modpack worked perfectly fine before (I got kiwi, NEC & sodium in it).

Is there another dependency that I have to download now? I noticed you put 'Added dependencies' in the latest changelog but there's no new dependencies in your curseforge's relations tab.

**Comment by ZestyBlaze** [comment]
I think you've got a corrupted config somewhere, can you go back a version of Capybara and see if these crashes still pop up? I can't see anything to do with Capybara in the crash logs but I'll reproduce this on a development environment with Kiwi and Sodium too

**Comment by ZestyBlaze** [comment]
Nevermind I think I found the cause, going to release a new file now, update it and try it again?

**Comment by Cynicizm** [comment]
> Nevermind I think I found the cause, going to release a new file now, update it and try it again?

Yup it works now. Thanks! :)

**Comment by ZestyBlaze** [comment]
\:)
