### ISSUE TITLE
Capybaras missing in the jungle

### ISSUE THREAD

**Issue by zimbal11** [ZestyBlaze/Capybara-UAM#24]
I only see the vanilla mobs in the jungle like parrots  but i cant find any capybaras, and i have tested the mod in a single biome only world with the jungle but the capybaras won't spawn

**Comment by ZestyBlaze** [comment]
Hm interesting, I'll investigate but I usually see them when I test
What mod version and minecraft version please?

**Comment by zimbal11** [comment]
Im using minecraft 1.19.3 with the capybara mod version 2.0.1

**Comment by zimbal11** [comment]
I played for 1 hour now and some capybaras spawned in the water i think i just need to increase the spawn weight

**Comment by zimbal11** [comment]
btw the capybaras only spawn on water in the jungle? because i cant find any in the jungle without water areas
