### ISSUE TITLE
Capybara Spatial Sound Incorrect

### ISSUE THREAD

**Issue by RotokEralil** [ZestyBlaze/Capybara-UAM#3]
Issue with the sounds Capybaras make not being directional and not reducing with distance (I get within range and they sound like they are 1 foot directly infront of me).

Were the sounds exported as stereo? 
(from another forum, "I figured out the reason. Looking through all of Minecraft's sound files, I noticed they were all saved as mono files with only one sound channel (instead of stereo with 2 channels, one for each ear). I think this is the reason why all of my sounds, which were all exported in stereo, always play in both ears with no spacial awareness")

**Comment by ZestyBlaze** [comment]
This is personally something that will need to be raised [here](https://github.com/TeamDraco/UnnamedAnimalMod) due to the fact that the Capybara is just a port from this mod, so all the sound files came from there too

**Comment by RotokEralil** [comment]
> This is personally something that will need to be raised [here](https://github.com/TeamDraco/UnnamedAnimalMod) due to the fact that the Capybara is just a port from this mod, so all the sound files came from there too

It's a pretty simple fix, you can do it in audacity (free sound editor). I can even do it and send you the updated file

**Comment by dvitski** [comment]
The point still stands

**Comment by RotokEralil** [comment]
> The point still stands

You are not allowed to fix an error in the sound file?

**Comment by dvitski** [comment]
The idea is that changes are to be made to the main mod, then ported to this version. Issues should be reported to that main mod.

**Comment by RotokEralil** [comment]
Apologies; was unfamiliar with your workflow process.
Love the mod! Have a wonderful day!
