### ISSUE TITLE
Capybara won't drop items upon death

### ISSUE THREAD

**Issue by ApoWillow** [ZestyBlaze/Capybara-UAM#4]
If a capybara has a chest with items in it, it will not drop the items upon death, I would appreciate if there is a update that fixes this problem soon :D

**Comment by ZestyBlaze** [comment]
I personally don't know if they do that in the original mod which this is originally a fork of so I'll have to do some investigation

**Comment by Redd56** [comment]
well thats a vanilla feature with donkeys and mules. so it should happen. thats just deletion of items otherwise

**Comment by ZestyBlaze** [comment]
Resolved in latest commit
