### ISSUE TITLE
Other Mobs will automatically ride the Capybara

### ISSUE THREAD

**Issue by Rayxanber** [ZestyBlaze/Capybara-UAM#7]
Unsure if this is intentional, and honestly, it isn't a big deal if it isn't, but other mobs (chickens, cats, etc) will automatically "mount" the Capybaras, the behavior is almost identical to mobs riding in boats. It's pretty hilarious, and honestly isn't a big deal but just thought I should point it out in case you didn't intend for it to be that way xD
![Untitled](https://user-images.githubusercontent.com/67816960/159113268-fcb78601-d06e-4010-b902-78f5e9185b8f.png)

**Comment by ZestyBlaze** [comment]
Yeah no that is intentional, that's a part of the code XD
